version: "3.3"
services:
  web:
    env_file: .env
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - dockerNet
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: wbd_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    networks:
      - dockerNet
networks:
  dockerNet:
    external:
      true
