<div class="top-bar">
    <!-- make template -->
    <nav class="top-bar-contents">
        <div class="cluster-h cluster-logo">
            <div>    
                logo
            </div>
            <div>
                title
            </div>
        </div>
        <div class="cluster-h cluster-search">
            <div class="search-container-small">
                <div class="input-group search-bar-small">
                    <input searchdata type="text" class=input-full>
                    <span class="placeholder">Search...</span>
                    <span class="search-icon">O</span>
                </div>
                <div class="search-result-small">
                    <!-- generated by search result -->
                </div>
            </div>    
            <div class="cluster-h cluster-login">
                <button class="button button-small button-grey"
                    onclick="location.href='/login'">
                    Log in
                </button>
                <button class="button button-small button-yellow" onclick="location.href='/register'">
                    Sign up
                </button>
            </div>
        </div>
    </nav>
<!-- make template -->
</div>